name: Local CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: self-hosted  # Use self-hosted runner instead of ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load environment variables
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t $DOCKER_USERNAME/collab-doc-backend:latest ./backend
          docker push $DOCKER_USERNAME/collab-doc-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t $DOCKER_USERNAME/collab-doc-frontend:latest ./frontend
          docker push $DOCKER_USERNAME/collab-doc-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Load environment variables
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Run Docker Compose locally
        run: |
          docker-compose down
          docker-compose up -d
