name: Local CI/CD Pipeline 2

on:
  push:
    branches:
      - main  # Trigger pipeline when code is pushed to 'main' branch

jobs:
  build-and-push:
    runs-on: self-hosted  # Use self-hosted runner instead of ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variables
        run: |
          echo "DOCKER_USERNAME=akshaurya" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=Aman@56884486" >> $GITHUB_ENV
          echo "JWT_SECRET=9bb218dd821b29f30145a70da5abdd9c999318c7dedaab564139764e20f8e8660f216c5e1cfd9a4a40e65bf9e4a3b9b7a8048efff53f92a1f4e99d742dc2e400" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/collab-docs?authSource=admin" >> $GITHUB_ENV
          echo "FRONTEND_URL=http://localhost:80" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t akshaurya/collab-doc-backend:latest ./backend
          docker push akshaurya/collab-doc-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t akshaurya/collab-doc-frontend:latest ./frontend
          docker push akshaurya/collab-doc-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "DOCKER_USERNAME=akshaurya" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=Aman@4486" >> $GITHUB_ENV
          echo "JWT_SECRET=9bb218dd821b29f30145a70da5abdd9c999318c7dedaab564139764e20f8e8660f216c5e1cfd9a4a40e65bf9e4a3b9b7a8048efff53f92a1f4e99d742dc2e400" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/collab-docs?authSource=admin" >> $GITHUB_ENV
          echo "FRONTEND_URL=http://localhost:80" >> $GITHUB_ENV

      - name: Stop running containers
        run: docker-compose down

      - name: Deploy new containers
        run: docker-compose up -d
