name: Local CI/CD Pipeline 2

on:
  push:
    branches:
      - main  # Trigger pipeline when code is pushed to 'main' branch

jobs:
  build-and-push:
    runs-on: self-hosted  # Use self-hosted runner instead of ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load environment variables
        run: |
          echo "Loading environment variables"
          set -o allexport
          source .env
          set +o allexport

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t $DOCKER_USERNAME/collab-doc-backend:latest ./backend
          docker push $DOCKER_USERNAME/collab-doc-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t $DOCKER_USERNAME/collab-doc-frontend:latest ./frontend
          docker push $DOCKER_USERNAME/collab-doc-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          echo "Loading environment variables"
          set -o allexport
          source .env
          set +o allexport

      - name: Stop running containers
        run: docker-compose down

      - name: Deploy new containers
        run: docker-compose up -d
